export default {
    //USER
    CHANGE_USER_DATA: 'CHANGE_USER_DATA',
    SET_USER_DATA: 'SET_USER_DATA',

    //QUIZ DATA
    SET_QUIZ_RESULTS: 'SET_QUIZ_RESULTS',

    //QUIZ QUESTIONS
    FETCH_QUIZ_QUESTIONS: 'FETCH_QUIZ_QUESTIONS',
    FETCH_QUIZ_QUESTIONS_ERROR: 'FETCH_QUIZ_QUESTIONS_ERROR',
    CLEAR_QUIZ_QUESTIONS: 'CLEAR_QUIZ_QUESTIONS',

    //THEMATICS
    GET_THEMATIC: 'GET_THEMATIC',
    GET_THEMATIC_ERROR: 'GET_THEMATIC_ERROR',
    SET_USER_CHOICE: 'SET_USER_CHOICE',
    CLEAR_THEMATICS: 'CLEAR_THEMATICS',

    //AUTHORIZATION
    USER_IN: 'USER_IN',
    USER_OUT: 'USER_OUT'
}